#############################################################################
# Makefile for building: IGITBuildingReconstruction
# Generated by qmake (2.01a) (Qt 4.8.1) on: Wed Nov 5 17:05:12 2014
# Project:  IGITBuildingReconstruction.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile IGITBuildingReconstruction.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_QT3SUPPORT_LIB -DQT3_SUPPORT -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -frounding-math -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/Qt3Support -I/usr/include/qt4 -I. -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4 -I/usr/include/qt3/ -I/usr/include/qt4/QtXml -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -L/usr/X11R6/lib64 -lQtOpenGL -lQGLViewer -lglut -lGL -lGLU -lQt3Support -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		sw_glviewer.cpp \
		sw_dataType.cpp \
		sw_mainwindow.cpp \
		sw_plyio.cpp moc_sw_glviewer.cpp \
		moc_sw_mainwindow.cpp \
		moc_sw_plyio.cpp
OBJECTS       = main.o \
		sw_glviewer.o \
		sw_dataType.o \
		sw_mainwindow.o \
		sw_plyio.o \
		moc_sw_glviewer.o \
		moc_sw_mainwindow.o \
		moc_sw_plyio.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		IGITBuildingReconstruction.pro
QMAKE_TARGET  = IGITBuildingReconstruction
DESTDIR       = 
TARGET        = IGITBuildingReconstruction

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: IGITBuildingReconstruction.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtOpenGL.prl \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl \
		/usr/lib/x86_64-linux-gnu/libQt3Support.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile IGITBuildingReconstruction.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtOpenGL.prl:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
/usr/lib/x86_64-linux-gnu/libQt3Support.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile IGITBuildingReconstruction.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/IGITBuildingReconstruction1.0.0 || $(MKDIR) .tmp/IGITBuildingReconstruction1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/IGITBuildingReconstruction1.0.0/ && $(COPY_FILE) --parents sw_dataType.h sw_glviewer.h sw_mainwindow.h sw_plyio.h .tmp/IGITBuildingReconstruction1.0.0/ && $(COPY_FILE) --parents main.cpp sw_glviewer.cpp sw_dataType.cpp sw_mainwindow.cpp sw_plyio.cpp .tmp/IGITBuildingReconstruction1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/IGITBuildingReconstruction1.0.0/ && (cd `dirname .tmp/IGITBuildingReconstruction1.0.0` && $(TAR) IGITBuildingReconstruction1.0.0.tar IGITBuildingReconstruction1.0.0 && $(COMPRESS) IGITBuildingReconstruction1.0.0.tar) && $(MOVE) `dirname .tmp/IGITBuildingReconstruction1.0.0`/IGITBuildingReconstruction1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/IGITBuildingReconstruction1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_sw_glviewer.cpp moc_sw_mainwindow.cpp moc_sw_plyio.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_sw_glviewer.cpp moc_sw_mainwindow.cpp moc_sw_plyio.cpp
moc_sw_glviewer.cpp: sw_glviewer.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) sw_glviewer.h -o moc_sw_glviewer.cpp

moc_sw_mainwindow.cpp: sw_dataType.h \
		sw_glviewer.h \
		ui_mainwindow.h \
		sw_mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) sw_mainwindow.h -o moc_sw_mainwindow.cpp

moc_sw_plyio.cpp: sw_plyio.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) sw_plyio.h -o moc_sw_plyio.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		sw_glviewer.h
	/usr/bin/uic-qt4 mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp sw_mainwindow.h \
		sw_dataType.h \
		sw_glviewer.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

sw_glviewer.o: sw_glviewer.cpp sw_glviewer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sw_glviewer.o sw_glviewer.cpp

sw_dataType.o: sw_dataType.cpp sw_dataType.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sw_dataType.o sw_dataType.cpp

sw_mainwindow.o: sw_mainwindow.cpp sw_mainwindow.h \
		sw_dataType.h \
		sw_glviewer.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sw_mainwindow.o sw_mainwindow.cpp

sw_plyio.o: sw_plyio.cpp sw_plyio.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sw_plyio.o sw_plyio.cpp

moc_sw_glviewer.o: moc_sw_glviewer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sw_glviewer.o moc_sw_glviewer.cpp

moc_sw_mainwindow.o: moc_sw_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sw_mainwindow.o moc_sw_mainwindow.cpp

moc_sw_plyio.o: moc_sw_plyio.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sw_plyio.o moc_sw_plyio.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

