######################################################################
# Automatically generated by qmake (2.01a) Sun Nov 9 20:28:41 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
FORMS += FloorPlan.ui
